CREATE TABLE gogoke_context_promotion_authorizations (
    domain_id TEXT NOT NULL,
    operation_id TEXT NOT NULL,
    context_id TEXT NOT NULL,
    version TEXT NOT NULL,
    context_fingerprint TEXT NOT NULL CHECK(length(context_fingerprint)=71),
    principal_id TEXT NOT NULL,
    seat_id TEXT NOT NULL,
    source_domain_id TEXT NOT NULL,
    source_context_id TEXT NOT NULL,
    source_version TEXT NOT NULL,
    source_content_hash TEXT NOT NULL CHECK(length(source_content_hash)=71),
    source_access_policy_revision TEXT NOT NULL,
    destination_scope TEXT NOT NULL CHECK(destination_scope='GLOBAL'),
    promotion_kind TEXT NOT NULL,
    source_grant_id TEXT NOT NULL,
    source_grant_revision TEXT NOT NULL,
    target_grant_id TEXT NOT NULL,
    target_grant_revision TEXT NOT NULL,
    policy_revision TEXT NOT NULL,
    revocation_head TEXT NOT NULL,
    request_fingerprint TEXT NOT NULL CHECK(length(request_fingerprint)=71),
    PRIMARY KEY(domain_id,operation_id),
    UNIQUE(domain_id,context_id,version),
    FOREIGN KEY(domain_id,operation_id) REFERENCES gogoke_context_operations(domain_id,operation_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY(domain_id,context_id,version) REFERENCES gogoke_context_versions(domain_id,context_id,version) ON DELETE RESTRICT ON UPDATE RESTRICT
) STRICT
